// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"planeo/services/email/internal/domain/mail"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// SaveFetchedMails provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveFetchedMails(ctx context.Context, mails []mail.FetchedMail) ([]mail.SaveResult, error) {
	ret := _mock.Called(ctx, mails)

	if len(ret) == 0 {
		panic("no return value specified for SaveFetchedMails")
	}

	var r0 []mail.SaveResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []mail.FetchedMail) ([]mail.SaveResult, error)); ok {
		return returnFunc(ctx, mails)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []mail.FetchedMail) []mail.SaveResult); ok {
		r0 = returnFunc(ctx, mails)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mail.SaveResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []mail.FetchedMail) error); ok {
		r1 = returnFunc(ctx, mails)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_SaveFetchedMails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFetchedMails'
type MockRepository_SaveFetchedMails_Call struct {
	*mock.Call
}

// SaveFetchedMails is a helper method to define mock.On call
//   - ctx context.Context
//   - mails []mail.FetchedMail
func (_e *MockRepository_Expecter) SaveFetchedMails(ctx interface{}, mails interface{}) *MockRepository_SaveFetchedMails_Call {
	return &MockRepository_SaveFetchedMails_Call{Call: _e.mock.On("SaveFetchedMails", ctx, mails)}
}

func (_c *MockRepository_SaveFetchedMails_Call) Run(run func(ctx context.Context, mails []mail.FetchedMail)) *MockRepository_SaveFetchedMails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []mail.FetchedMail
		if args[1] != nil {
			arg1 = args[1].([]mail.FetchedMail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SaveFetchedMails_Call) Return(saveResults []mail.SaveResult, err error) *MockRepository_SaveFetchedMails_Call {
	_c.Call.Return(saveResults, err)
	return _c
}

func (_c *MockRepository_SaveFetchedMails_Call) RunAndReturn(run func(ctx context.Context, mails []mail.FetchedMail) ([]mail.SaveResult, error)) *MockRepository_SaveFetchedMails_Call {
	_c.Call.Return(run)
	return _c
}
