// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"planeo/services/email/internal/domain/mail"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateMail provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateMail(ctx context.Context, m mail.NewMail) (int, bool, error) {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for CreateMail")
	}

	var r0 int
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mail.NewMail) (int, bool, error)); ok {
		return returnFunc(ctx, m)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mail.NewMail) int); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mail.NewMail) bool); ok {
		r1 = returnFunc(ctx, m)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, mail.NewMail) error); ok {
		r2 = returnFunc(ctx, m)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_CreateMail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMail'
type MockRepository_CreateMail_Call struct {
	*mock.Call
}

// CreateMail is a helper method to define mock.On call
//   - ctx context.Context
//   - m mail.NewMail
func (_e *MockRepository_Expecter) CreateMail(ctx interface{}, m interface{}) *MockRepository_CreateMail_Call {
	return &MockRepository_CreateMail_Call{Call: _e.mock.On("CreateMail", ctx, m)}
}

func (_c *MockRepository_CreateMail_Call) Run(run func(ctx context.Context, m mail.NewMail)) *MockRepository_CreateMail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mail.NewMail
		if args[1] != nil {
			arg1 = args[1].(mail.NewMail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateMail_Call) Return(mailID int, inserted bool, err error) *MockRepository_CreateMail_Call {
	_c.Call.Return(mailID, inserted, err)
	return _c
}

func (_c *MockRepository_CreateMail_Call) RunAndReturn(run func(ctx context.Context, m mail.NewMail) (int, bool, error)) *MockRepository_CreateMail_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOutboxEvent provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateOutboxEvent(ctx context.Context, mailID int, event mail.OutboxEvent) error {
	ret := _mock.Called(ctx, mailID, event)

	if len(ret) == 0 {
		panic("no return value specified for CreateOutboxEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, mail.OutboxEvent) error); ok {
		r0 = returnFunc(ctx, mailID, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateOutboxEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOutboxEvent'
type MockRepository_CreateOutboxEvent_Call struct {
	*mock.Call
}

// CreateOutboxEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - mailID int
//   - event mail.OutboxEvent
func (_e *MockRepository_Expecter) CreateOutboxEvent(ctx interface{}, mailID interface{}, event interface{}) *MockRepository_CreateOutboxEvent_Call {
	return &MockRepository_CreateOutboxEvent_Call{Call: _e.mock.On("CreateOutboxEvent", ctx, mailID, event)}
}

func (_c *MockRepository_CreateOutboxEvent_Call) Run(run func(ctx context.Context, mailID int, event mail.OutboxEvent)) *MockRepository_CreateOutboxEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 mail.OutboxEvent
		if args[2] != nil {
			arg2 = args[2].(mail.OutboxEvent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_CreateOutboxEvent_Call) Return(err error) *MockRepository_CreateOutboxEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateOutboxEvent_Call) RunAndReturn(run func(ctx context.Context, mailID int, event mail.OutboxEvent) error) *MockRepository_CreateOutboxEvent_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type MockRepository
func (_mock *MockRepository) WithTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockRepository_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockRepository_Expecter) WithTransaction(ctx interface{}, fn interface{}) *MockRepository_WithTransaction_Call {
	return &MockRepository_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *MockRepository_WithTransaction_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockRepository_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_WithTransaction_Call) Return(err error) *MockRepository_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockRepository_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
