// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"planeo/services/email/internal/domain/mail"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// SaveFetchedMails provides a mock function for the type MockService
func (_mock *MockService) SaveFetchedMails(ctx context.Context, raws []mail.RawFetchedMail) ([]mail.SaveResult, error) {
	ret := _mock.Called(ctx, raws)

	if len(ret) == 0 {
		panic("no return value specified for SaveFetchedMails")
	}

	var r0 []mail.SaveResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []mail.RawFetchedMail) ([]mail.SaveResult, error)); ok {
		return returnFunc(ctx, raws)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []mail.RawFetchedMail) []mail.SaveResult); ok {
		r0 = returnFunc(ctx, raws)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mail.SaveResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []mail.RawFetchedMail) error); ok {
		r1 = returnFunc(ctx, raws)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SaveFetchedMails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFetchedMails'
type MockService_SaveFetchedMails_Call struct {
	*mock.Call
}

// SaveFetchedMails is a helper method to define mock.On call
//   - ctx context.Context
//   - raws []mail.RawFetchedMail
func (_e *MockService_Expecter) SaveFetchedMails(ctx interface{}, raws interface{}) *MockService_SaveFetchedMails_Call {
	return &MockService_SaveFetchedMails_Call{Call: _e.mock.On("SaveFetchedMails", ctx, raws)}
}

func (_c *MockService_SaveFetchedMails_Call) Run(run func(ctx context.Context, raws []mail.RawFetchedMail)) *MockService_SaveFetchedMails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []mail.RawFetchedMail
		if args[1] != nil {
			arg1 = args[1].([]mail.RawFetchedMail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_SaveFetchedMails_Call) Return(saveResults []mail.SaveResult, err error) *MockService_SaveFetchedMails_Call {
	_c.Call.Return(saveResults, err)
	return _c
}

func (_c *MockService_SaveFetchedMails_Call) RunAndReturn(run func(ctx context.Context, raws []mail.RawFetchedMail) ([]mail.SaveResult, error)) *MockService_SaveFetchedMails_Call {
	_c.Call.Return(run)
	return _c
}
