// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// ProduceSync provides a mock function for the type MockProducer
func (_mock *MockProducer) ProduceSync(ctx context.Context, topic string, key []byte, value []byte) error {
	ret := _mock.Called(ctx, topic, key, value)

	if len(ret) == 0 {
		panic("no return value specified for ProduceSync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, []byte) error); ok {
		r0 = returnFunc(ctx, topic, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducer_ProduceSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceSync'
type MockProducer_ProduceSync_Call struct {
	*mock.Call
}

// ProduceSync is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - key []byte
//   - value []byte
func (_e *MockProducer_Expecter) ProduceSync(ctx interface{}, topic interface{}, key interface{}, value interface{}) *MockProducer_ProduceSync_Call {
	return &MockProducer_ProduceSync_Call{Call: _e.mock.On("ProduceSync", ctx, topic, key, value)}
}

func (_c *MockProducer_ProduceSync_Call) Run(run func(ctx context.Context, topic string, key []byte, value []byte)) *MockProducer_ProduceSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProducer_ProduceSync_Call) Return(err error) *MockProducer_ProduceSync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducer_ProduceSync_Call) RunAndReturn(run func(ctx context.Context, topic string, key []byte, value []byte) error) *MockProducer_ProduceSync_Call {
	_c.Call.Return(run)
	return _c
}
