// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"planeo/services/core2/internal/domain/request"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRequestRepository creates a new instance of MockRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestRepository {
	mock := &MockRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRequestRepository is an autogenerated mock type for the RequestRepository type
type MockRequestRepository struct {
	mock.Mock
}

type MockRequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestRepository) EXPECT() *MockRequestRepository_Expecter {
	return &MockRequestRepository_Expecter{mock: &_m.Mock}
}

// CreateRequest provides a mock function for the type MockRequestRepository
func (_mock *MockRequestRepository) CreateRequest(ctx context.Context, request1 request.NewRequest) (int, error) {
	ret := _mock.Called(ctx, request1)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequest")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.NewRequest) (int, error)); ok {
		return returnFunc(ctx, request1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.NewRequest) int); ok {
		r0 = returnFunc(ctx, request1)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.NewRequest) error); ok {
		r1 = returnFunc(ctx, request1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestRepository_CreateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRequest'
type MockRequestRepository_CreateRequest_Call struct {
	*mock.Call
}

// CreateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - request1 request.NewRequest
func (_e *MockRequestRepository_Expecter) CreateRequest(ctx interface{}, request1 interface{}) *MockRequestRepository_CreateRequest_Call {
	return &MockRequestRepository_CreateRequest_Call{Call: _e.mock.On("CreateRequest", ctx, request1)}
}

func (_c *MockRequestRepository_CreateRequest_Call) Run(run func(ctx context.Context, request1 request.NewRequest)) *MockRequestRepository_CreateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.NewRequest
		if args[1] != nil {
			arg1 = args[1].(request.NewRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequestRepository_CreateRequest_Call) Return(n int, err error) *MockRequestRepository_CreateRequest_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRequestRepository_CreateRequest_Call) RunAndReturn(run func(ctx context.Context, request1 request.NewRequest) (int, error)) *MockRequestRepository_CreateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRequest provides a mock function for the type MockRequestRepository
func (_mock *MockRequestRepository) DeleteRequest(ctx context.Context, organizationId int, requestId int) error {
	ret := _mock.Called(ctx, organizationId, requestId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, organizationId, requestId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRequestRepository_DeleteRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRequest'
type MockRequestRepository_DeleteRequest_Call struct {
	*mock.Call
}

// DeleteRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - requestId int
func (_e *MockRequestRepository_Expecter) DeleteRequest(ctx interface{}, organizationId interface{}, requestId interface{}) *MockRequestRepository_DeleteRequest_Call {
	return &MockRequestRepository_DeleteRequest_Call{Call: _e.mock.On("DeleteRequest", ctx, organizationId, requestId)}
}

func (_c *MockRequestRepository_DeleteRequest_Call) Run(run func(ctx context.Context, organizationId int, requestId int)) *MockRequestRepository_DeleteRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRequestRepository_DeleteRequest_Call) Return(err error) *MockRequestRepository_DeleteRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRequestRepository_DeleteRequest_Call) RunAndReturn(run func(ctx context.Context, organizationId int, requestId int) error) *MockRequestRepository_DeleteRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequest provides a mock function for the type MockRequestRepository
func (_mock *MockRequestRepository) GetRequest(ctx context.Context, organizationId int, requestId int) (request.Request, error) {
	ret := _mock.Called(ctx, organizationId, requestId)

	if len(ret) == 0 {
		panic("no return value specified for GetRequest")
	}

	var r0 request.Request
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (request.Request, error)); ok {
		return returnFunc(ctx, organizationId, requestId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) request.Request); ok {
		r0 = returnFunc(ctx, organizationId, requestId)
	} else {
		r0 = ret.Get(0).(request.Request)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, organizationId, requestId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestRepository_GetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequest'
type MockRequestRepository_GetRequest_Call struct {
	*mock.Call
}

// GetRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - requestId int
func (_e *MockRequestRepository_Expecter) GetRequest(ctx interface{}, organizationId interface{}, requestId interface{}) *MockRequestRepository_GetRequest_Call {
	return &MockRequestRepository_GetRequest_Call{Call: _e.mock.On("GetRequest", ctx, organizationId, requestId)}
}

func (_c *MockRequestRepository_GetRequest_Call) Run(run func(ctx context.Context, organizationId int, requestId int)) *MockRequestRepository_GetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRequestRepository_GetRequest_Call) Return(request1 request.Request, err error) *MockRequestRepository_GetRequest_Call {
	_c.Call.Return(request1, err)
	return _c
}

func (_c *MockRequestRepository_GetRequest_Call) RunAndReturn(run func(ctx context.Context, organizationId int, requestId int) (request.Request, error)) *MockRequestRepository_GetRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequests provides a mock function for the type MockRequestRepository
func (_mock *MockRequestRepository) GetRequests(ctx context.Context, organizationId int, cursor int, limit int, getClosed bool, selectedCategories []int) ([]request.Request, error) {
	ret := _mock.Called(ctx, organizationId, cursor, limit, getClosed, selectedCategories)

	if len(ret) == 0 {
		panic("no return value specified for GetRequests")
	}

	var r0 []request.Request
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int, bool, []int) ([]request.Request, error)); ok {
		return returnFunc(ctx, organizationId, cursor, limit, getClosed, selectedCategories)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int, bool, []int) []request.Request); ok {
		r0 = returnFunc(ctx, organizationId, cursor, limit, getClosed, selectedCategories)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]request.Request)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, int, bool, []int) error); ok {
		r1 = returnFunc(ctx, organizationId, cursor, limit, getClosed, selectedCategories)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestRepository_GetRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequests'
type MockRequestRepository_GetRequests_Call struct {
	*mock.Call
}

// GetRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - cursor int
//   - limit int
//   - getClosed bool
//   - selectedCategories []int
func (_e *MockRequestRepository_Expecter) GetRequests(ctx interface{}, organizationId interface{}, cursor interface{}, limit interface{}, getClosed interface{}, selectedCategories interface{}) *MockRequestRepository_GetRequests_Call {
	return &MockRequestRepository_GetRequests_Call{Call: _e.mock.On("GetRequests", ctx, organizationId, cursor, limit, getClosed, selectedCategories)}
}

func (_c *MockRequestRepository_GetRequests_Call) Run(run func(ctx context.Context, organizationId int, cursor int, limit int, getClosed bool, selectedCategories []int)) *MockRequestRepository_GetRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 []int
		if args[5] != nil {
			arg5 = args[5].([]int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockRequestRepository_GetRequests_Call) Return(requests []request.Request, err error) *MockRequestRepository_GetRequests_Call {
	_c.Call.Return(requests, err)
	return _c
}

func (_c *MockRequestRepository_GetRequests_Call) RunAndReturn(run func(ctx context.Context, organizationId int, cursor int, limit int, getClosed bool, selectedCategories []int) ([]request.Request, error)) *MockRequestRepository_GetRequests_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRequest provides a mock function for the type MockRequestRepository
func (_mock *MockRequestRepository) UpdateRequest(ctx context.Context, request1 request.UpdateRequest) error {
	ret := _mock.Called(ctx, request1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.UpdateRequest) error); ok {
		r0 = returnFunc(ctx, request1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRequestRepository_UpdateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRequest'
type MockRequestRepository_UpdateRequest_Call struct {
	*mock.Call
}

// UpdateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - request1 request.UpdateRequest
func (_e *MockRequestRepository_Expecter) UpdateRequest(ctx interface{}, request1 interface{}) *MockRequestRepository_UpdateRequest_Call {
	return &MockRequestRepository_UpdateRequest_Call{Call: _e.mock.On("UpdateRequest", ctx, request1)}
}

func (_c *MockRequestRepository_UpdateRequest_Call) Run(run func(ctx context.Context, request1 request.UpdateRequest)) *MockRequestRepository_UpdateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.UpdateRequest
		if args[1] != nil {
			arg1 = args[1].(request.UpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequestRepository_UpdateRequest_Call) Return(err error) *MockRequestRepository_UpdateRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRequestRepository_UpdateRequest_Call) RunAndReturn(run func(ctx context.Context, request1 request.UpdateRequest) error) *MockRequestRepository_UpdateRequest_Call {
	_c.Call.Return(run)
	return _c
}
