quiet: False
disable-version-string: True
with-expecter: True
filename: "mock_{{.InterfaceName | snakecase}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
all: true
packages:
  planeo/api/internal/resources/user:
    # place your package-specific config here
    config:
    interfaces:
      # select the interfaces you want mocked
      UserRepositoryInterface:
        # Modify package-level config for this specific interface (if applicable)
        config:
      IAMRepositoryInterface:
        config:
  planeo/api/internal/resources/request:
    config:
    interfaces:
      RequestRepositoryInterface:
        config:
  planeo/api/internal/resources/category:
    config:
    interfaces:
      CategoryRepositoryInterface:
        config:
