// This file is auto-generated by @hey-api/openapi-ts

export type Category = {
    Color: string;
    CreatedAt: string;
    Id: number;
    Label: string;
    LabelDescription: string;
    OrganizationId: number;
    UpdatedAt: string;
};

export type CreateCategoryInputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    color: string;
    label: string;
    labelDescription: string;
};

export type CreateCategoryInputBodyWritable = {
    color: string;
    label: string;
    labelDescription: string;
};

export type CreateCategoryOutputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * ID of the created category
     */
    id: number;
};

export type CreateCategoryOutputBodyWritable = {
    /**
     * ID of the created category
     */
    id: number;
};

export type CreateRequestInputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Address of the requester
     */
    address: string;
    /**
     * Identifier of the category
     */
    categoryId?: number;
    /**
     * Indicates if the request is closed
     */
    closed: boolean;
    /**
     * Email of the requester
     */
    email: string;
    /**
     * Name of the requester
     */
    name: string;
    /**
     * Subject of the request
     */
    subject: string;
    /**
     * Telephone number of the requester
     */
    telephone: string;
    /**
     * Description of the request
     */
    text: string;
};

export type CreateRequestInputBodyWritable = {
    /**
     * Address of the requester
     */
    address: string;
    /**
     * Identifier of the category
     */
    categoryId?: number;
    /**
     * Indicates if the request is closed
     */
    closed: boolean;
    /**
     * Email of the requester
     */
    email: string;
    /**
     * Name of the requester
     */
    name: string;
    /**
     * Subject of the request
     */
    subject: string;
    /**
     * Telephone number of the requester
     */
    telephone: string;
    /**
     * Description of the request
     */
    text: string;
};

export type CreateRequestOutputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * ID of the created category
     */
    id: number;
};

export type CreateRequestOutputBodyWritable = {
    /**
     * ID of the created category
     */
    id: number;
};

export type CreateUserInputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Email of the user to be created
     */
    email: string;
    /**
     * First name of the user to be created
     */
    firstName: string;
    /**
     * Last name of the user to be created
     */
    lastName: string;
    /**
     * Initial password for the user to be set
     */
    password: string;
};

export type CreateUserInputBodyWritable = {
    /**
     * Email of the user to be created
     */
    email: string;
    /**
     * First name of the user to be created
     */
    firstName: string;
    /**
     * Last name of the user to be created
     */
    lastName: string;
    /**
     * Initial password for the user to be set
     */
    password: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModelReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type GetCategoriesOutputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Array of categories
     */
    categories: Array<Category> | null;
};

export type GetCategoriesOutputBodyWritable = {
    /**
     * Array of categories
     */
    categories: Array<Category> | null;
};

export type GetIamUserOutputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Information about a user managed in given auth system
     */
    user: IamUser;
};

export type GetIamUserOutputBodyWritable = {
    /**
     * Information about a user managed in given auth system
     */
    user: IamUser;
};

export type GetIamUsersOutputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Array of users managed in organization
     */
    users: Array<IamUser> | null;
};

export type GetIamUsersOutputBodyWritable = {
    /**
     * Array of users managed in organization
     */
    users: Array<IamUser> | null;
};

export type GetRequestsOutputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Number of requests to be returned
     */
    limit: number;
    /**
     * Cursor for pagination
     */
    nextCursor: number;
    /**
     * Array of requests
     */
    requests: Array<Request> | null;
};

export type GetRequestsOutputBodyWritable = {
    /**
     * Number of requests to be returned
     */
    limit: number;
    /**
     * Cursor for pagination
     */
    nextCursor: number;
    /**
     * Array of requests
     */
    requests: Array<Request> | null;
};

export type GetRolesOutputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Array of roles that can be assigned to users
     */
    roles: Array<Role> | null;
};

export type GetRolesOutputBodyWritable = {
    /**
     * Array of roles that can be assigned to users
     */
    roles: Array<Role> | null;
};

export type GetUsersOutputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Array of users with basic informations
     */
    users: Array<User> | null;
};

export type GetUsersOutputBodyWritable = {
    /**
     * Array of users with basic informations
     */
    users: Array<User> | null;
};

export type IamUser = {
    /**
     * Email of the user
     */
    email: string;
    /**
     * Flag describing whether user email is verified or not
     */
    emailVerified: boolean;
    /**
     * Flag describing whether user is active or not
     */
    enabled: boolean;
    /**
     * First name of the user
     */
    firstName: string;
    /**
     * Last name of the user
     */
    lastName: string;
    /**
     * Array of actions that will be conducted after login
     */
    requiredActions: Array<string> | null;
    /**
     * Array of roles assigned to the user
     */
    roles?: Array<Role> | null;
    /**
     * Flag describing whether TOTP was set or not
     */
    totp: boolean;
    /**
     * User name
     */
    username: string;
    /**
     * User identifier within the authentication system
     */
    uuid: string;
};

export type Organization = {
    address: string;
    created_at: string;
    email: string;
    iam_organization_id: string;
    id: number;
    name: string;
    updated_at: string;
};

export type PutUserRoleInputBody = {
    /**
     * ID of the role to be assigned to the user
     */
    id: string;
    /**
     * Name of the role to be assigned to the user
     */
    name: string;
};

export type Request = {
    Address: string;
    CategoryId: number | null;
    Closed: boolean;
    CreatedAt: string;
    Email: string;
    Id: number;
    Name: string;
    OrganizationId: number;
    Raw: string;
    ReferenceId: string;
    Subject: string;
    Telephone: string;
    Text: string;
    UpdatedAt: string;
};

export type Role = {
    /**
     * ID of the role to be assigned to the user
     */
    id: string;
    /**
     * Name of the role to be assigned to the user
     */
    name: string;
};

export type StatusOutputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Status of the API server
     */
    alive: boolean;
};

export type StatusOutputBodyWritable = {
    /**
     * Status of the API server
     */
    alive: boolean;
};

export type UpdateCategoryInputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    color: string;
    label: string;
    labelDescription: string;
};

export type UpdateCategoryInputBodyWritable = {
    color: string;
    label: string;
    labelDescription: string;
};

export type UpdateRequestInputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Address of the requester
     */
    address: string;
    /**
     * Identifier of the category
     */
    categoryId: number;
    /**
     * Indicates if the request is closed
     */
    closed: boolean;
    /**
     * Email of the requester
     */
    email: string;
    /**
     * Name of the requester
     */
    name: string;
    /**
     * Subject of the request
     */
    subject: string;
    /**
     * Telephone number of the requester
     */
    telephone: string;
    /**
     * Description of the request
     */
    text: string;
};

export type UpdateRequestInputBodyWritable = {
    /**
     * Address of the requester
     */
    address: string;
    /**
     * Identifier of the category
     */
    categoryId: number;
    /**
     * Indicates if the request is closed
     */
    closed: boolean;
    /**
     * Email of the requester
     */
    email: string;
    /**
     * Name of the requester
     */
    name: string;
    /**
     * Subject of the request
     */
    subject: string;
    /**
     * Telephone number of the requester
     */
    telephone: string;
    /**
     * Description of the request
     */
    text: string;
};

export type UpdateUserInputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Email of the user
     */
    email: string;
    /**
     * Flag describing whether user email is verified or not
     */
    emailVerified: boolean;
    /**
     * Flag describing whether user is active or not
     */
    enabled: boolean;
    /**
     * First name of the user
     */
    firstName: string;
    /**
     * Last name of the user
     */
    lastName: string;
    /**
     * Array of actions that will be conducted after login
     */
    requiredActions: Array<string> | null;
    /**
     * Flag describing whether TOTP was set or not
     */
    totp: boolean;
    /**
     * User name
     */
    username: string;
};

export type UpdateUserInputBodyWritable = {
    /**
     * Email of the user
     */
    email: string;
    /**
     * Flag describing whether user email is verified or not
     */
    emailVerified: boolean;
    /**
     * Flag describing whether user is active or not
     */
    enabled: boolean;
    /**
     * First name of the user
     */
    firstName: string;
    /**
     * Last name of the user
     */
    lastName: string;
    /**
     * Array of actions that will be conducted after login
     */
    requiredActions: Array<string> | null;
    /**
     * Flag describing whether TOTP was set or not
     */
    totp: boolean;
    /**
     * User name
     */
    username: string;
};

export type User = {
    /**
     * Timestamp when the user was created
     */
    createdAt: string;
    /**
     * Email of the user
     */
    email: string;
    /**
     * First name of the user
     */
    firstName: string;
    id: number;
    /**
     * Last name of the user
     */
    lastName: string;
    organization: number;
    /**
     * Timestamp when the user was last updated
     */
    updatedAt: string;
    /**
     * User name
     */
    username: string;
    /**
     * UUID of the user in the IAM system
     */
    uuid: string;
};

export type ServerStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type ServerStatusErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ServerStatusError = ServerStatusErrors[keyof ServerStatusErrors];

export type ServerStatusResponses = {
    /**
     * OK
     */
    200: StatusOutputBodyReadable;
};

export type ServerStatusResponse = ServerStatusResponses[keyof ServerStatusResponses];

export type GetOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/organizations';
};

export type GetOrganizationsErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetOrganizationsError = GetOrganizationsErrors[keyof GetOrganizationsErrors];

export type GetOrganizationsResponses = {
    /**
     * Array of organizations the user belongs to
     */
    200: Array<Organization> | null;
};

export type GetOrganizationsResponse = GetOrganizationsResponses[keyof GetOrganizationsResponses];

export type GetCategoriesData = {
    body?: never;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/categories';
};

export type GetCategoriesErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetCategoriesError = GetCategoriesErrors[keyof GetCategoriesErrors];

export type GetCategoriesResponses = {
    /**
     * OK
     */
    200: GetCategoriesOutputBodyReadable;
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type CreateCategoryData = {
    body: CreateCategoryInputBodyWritable;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/categories';
};

export type CreateCategoryErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type CreateCategoryError = CreateCategoryErrors[keyof CreateCategoryErrors];

export type CreateCategoryResponses = {
    /**
     * Created
     */
    201: CreateCategoryOutputBodyReadable;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
        /**
         * ID of the category
         */
        categoryId: number;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/categories/{categoryId}';
};

export type DeleteCategoryErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type DeleteCategoryError = DeleteCategoryErrors[keyof DeleteCategoryErrors];

export type DeleteCategoryResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteCategoryResponse = DeleteCategoryResponses[keyof DeleteCategoryResponses];

export type UpdateCategoryData = {
    body: UpdateCategoryInputBodyWritable;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
        /**
         * ID of the category
         */
        categoryId: number;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/categories/{categoryId}';
};

export type UpdateCategoryErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type UpdateCategoryError = UpdateCategoryErrors[keyof UpdateCategoryErrors];

export type UpdateCategoryResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateCategoryResponse = UpdateCategoryResponses[keyof UpdateCategoryResponses];

export type GetRolesData = {
    body?: never;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/iam/roles';
};

export type GetRolesErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetRolesError = GetRolesErrors[keyof GetRolesErrors];

export type GetRolesResponses = {
    /**
     * OK
     */
    200: GetRolesOutputBodyReadable;
};

export type GetRolesResponse = GetRolesResponses[keyof GetRolesResponses];

export type GetUsersData = {
    body?: never;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
    };
    query?: {
        /**
         * Flag describing whether to sync users from auth system or not
         */
        sync?: boolean;
    };
    url: '/v1/organizations/{organizationId}/iam/users';
};

export type GetUsersErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * OK
     */
    200: GetIamUsersOutputBodyReadable;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type CreateUserData = {
    body: CreateUserInputBodyWritable;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/iam/users';
};

export type CreateUserErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
        /**
         * IAM uuid of the user to be deleted
         */
        uuid: string;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/iam/users/{uuid}';
};

export type DeleteUserErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
        /**
         * IAM uuid of a user
         */
        uuid: string;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/iam/users/{uuid}';
};

export type GetUserErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * OK
     */
    200: GetIamUserOutputBodyReadable;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UpdateUserInputBodyWritable;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
        /**
         * IAM uuid of the user to be deleted
         */
        uuid: string;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/iam/users/{uuid}';
};

export type UpdateUserErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type AssignUserRolesData = {
    /**
     * Array of role representations
     */
    body: Array<PutUserRoleInputBody> | null;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
        /**
         * ID of the user to be deleted
         */
        uuid: string;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/iam/users/{uuid}/roles';
};

export type AssignUserRolesErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type AssignUserRolesError = AssignUserRolesErrors[keyof AssignUserRolesErrors];

export type AssignUserRolesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AssignUserRolesResponse = AssignUserRolesResponses[keyof AssignUserRolesResponses];

export type GetRequestsData = {
    body?: never;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
    };
    query: {
        /**
         * Flag describing whether to get also closed requests or not
         */
        getClosed?: boolean;
        /**
         * Number of requests to be returned
         */
        pageSize: number;
        /**
         * Cursor for pagination
         */
        cursor?: number;
        /**
         * Array of category IDs to filter requests by
         */
        selectedCategories?: Array<number> | null;
    };
    url: '/v1/organizations/{organizationId}/requests';
};

export type GetRequestsErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetRequestsError = GetRequestsErrors[keyof GetRequestsErrors];

export type GetRequestsResponses = {
    /**
     * OK
     */
    200: GetRequestsOutputBodyReadable;
};

export type GetRequestsResponse = GetRequestsResponses[keyof GetRequestsResponses];

export type CreateRequestData = {
    body: CreateRequestInputBodyWritable;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/requests';
};

export type CreateRequestErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type CreateRequestError = CreateRequestErrors[keyof CreateRequestErrors];

export type CreateRequestResponses = {
    /**
     * Created
     */
    201: CreateRequestOutputBodyReadable;
};

export type CreateRequestResponse = CreateRequestResponses[keyof CreateRequestResponses];

export type DeleteRequestData = {
    body?: never;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
        /**
         * ID of the request
         */
        requestId: number;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/requests/{requestId}';
};

export type DeleteRequestErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type DeleteRequestError = DeleteRequestErrors[keyof DeleteRequestErrors];

export type DeleteRequestResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRequestResponse = DeleteRequestResponses[keyof DeleteRequestResponses];

export type UpdateRequestData = {
    body: UpdateRequestInputBodyWritable;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
        /**
         * ID of the request
         */
        requestId: number;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/requests/{requestId}';
};

export type UpdateRequestErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type UpdateRequestError = UpdateRequestErrors[keyof UpdateRequestErrors];

export type UpdateRequestResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateRequestResponse = UpdateRequestResponses[keyof UpdateRequestResponses];

export type GetBasicUserInformationData = {
    body?: never;
    path: {
        /**
         * ID of the organization
         */
        organizationId: number;
    };
    query?: never;
    url: '/v1/organizations/{organizationId}/users';
};

export type GetBasicUserInformationErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetBasicUserInformationError = GetBasicUserInformationErrors[keyof GetBasicUserInformationErrors];

export type GetBasicUserInformationResponses = {
    /**
     * OK
     */
    200: GetUsersOutputBodyReadable;
};

export type GetBasicUserInformationResponse = GetBasicUserInformationResponses[keyof GetBasicUserInformationResponses];

export type ClientOptions = {
    baseURL: 'http://localhost/api' | (string & {});
};