services:
  ##### application related services #####
  postgres:
    image: postgres:alpine3.20
    container_name: postgres
    environment:
      POSTGRES_USER: planeo
      POSTGRES_PASSWORD: planeo
      POSTGRES_DB: planeo
    ports:
      - "5432:5432"
    volumes:
      - ./mail_service_init.sh:/docker-entrypoint-initdb.d/mail_service_init.sh
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: local@user.com
      PGADMIN_DEFAULT_PASSWORD: local
    volumes:
      - pg-data:/var/lib/pgadmin

  ##### Keycloak services #####
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: start-dev
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - 8080:8080
    restart: always

  # email services
  greenmail:
    image: greenmail/standalone:latest
    environment:
      - JAVA_OPTS=-Dgreenmail.verbose
    ports:
      - 3025:3025 # SMTP
      - 3110:3110 # POP3
      - 3143:3143 # IMAP
      - 3465:3465 # SMTPS
      - 3993:3993 # IMAPS
      - 3995:3995 # POP3S
      - 8088:8088 # API
  roundcube:
    image: roundcube/roundcubemail:latest
    depends_on:
      - greenmail
    ports:
      - 8089:80
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=greenmail # IMAP server - tls:// prefix for STARTTLS, ssl:// for SSL/TLS
      - ROUNDCUBEMAIL_DEFAULT_PORT=3143 # IMAP port
      - ROUNDCUBEMAIL_SMTP_SERVER=greenmail # SMTP server - tls:// prefix for STARTTLS, ssl:// for SSL/TLS
      - ROUNDCUBEMAIL_SMTP_PORT=3025 # SMTP port

# nats messaging (single node with JetStream)
  nats:
    container_name: nats
    image: nats
    entrypoint: /nats-server
    command: --server_name N1 --js --sd /data -p 4222
    ports:
      - 4222:4222
      - 8222:8222

networks:
  default:
    driver: bridge

# volumes for pgadmin,postgres and keycloak
volumes:
  pg-data:
