// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package tutorial

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64
	Name string
	Bio  pgtype.Text
}

type Book struct {
	ID     int64
	Name   string
	Author pgtype.Int8
}

type BooksWithAuthor struct {
	Books []string
	ID    int64
	Name  string
	Bio   pgtype.Text
}
