// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"planeo/services/core/internal/domain/category"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateCategory provides a mock function for the type MockService
func (_mock *MockService) CreateCategory(ctx context.Context, organizationId int, category1 category.NewCategory) (int, error) {
	ret := _mock.Called(ctx, organizationId, category1)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, category.NewCategory) (int, error)); ok {
		return returnFunc(ctx, organizationId, category1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, category.NewCategory) int); ok {
		r0 = returnFunc(ctx, organizationId, category1)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, category.NewCategory) error); ok {
		r1 = returnFunc(ctx, organizationId, category1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type MockService_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - category1 category.NewCategory
func (_e *MockService_Expecter) CreateCategory(ctx interface{}, organizationId interface{}, category1 interface{}) *MockService_CreateCategory_Call {
	return &MockService_CreateCategory_Call{Call: _e.mock.On("CreateCategory", ctx, organizationId, category1)}
}

func (_c *MockService_CreateCategory_Call) Run(run func(ctx context.Context, organizationId int, category1 category.NewCategory)) *MockService_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 category.NewCategory
		if args[2] != nil {
			arg2 = args[2].(category.NewCategory)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CreateCategory_Call) Return(n int, err error) *MockService_CreateCategory_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_CreateCategory_Call) RunAndReturn(run func(ctx context.Context, organizationId int, category1 category.NewCategory) (int, error)) *MockService_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCategory provides a mock function for the type MockService
func (_mock *MockService) DeleteCategory(ctx context.Context, organizationId int, categoryId int) error {
	ret := _mock.Called(ctx, organizationId, categoryId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, organizationId, categoryId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCategory'
type MockService_DeleteCategory_Call struct {
	*mock.Call
}

// DeleteCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - categoryId int
func (_e *MockService_Expecter) DeleteCategory(ctx interface{}, organizationId interface{}, categoryId interface{}) *MockService_DeleteCategory_Call {
	return &MockService_DeleteCategory_Call{Call: _e.mock.On("DeleteCategory", ctx, organizationId, categoryId)}
}

func (_c *MockService_DeleteCategory_Call) Run(run func(ctx context.Context, organizationId int, categoryId int)) *MockService_DeleteCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteCategory_Call) Return(err error) *MockService_DeleteCategory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteCategory_Call) RunAndReturn(run func(ctx context.Context, organizationId int, categoryId int) error) *MockService_DeleteCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategories provides a mock function for the type MockService
func (_mock *MockService) GetCategories(ctx context.Context, organizationId int) ([]category.Category, error) {
	ret := _mock.Called(ctx, organizationId)

	if len(ret) == 0 {
		panic("no return value specified for GetCategories")
	}

	var r0 []category.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]category.Category, error)); ok {
		return returnFunc(ctx, organizationId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []category.Category); ok {
		r0 = returnFunc(ctx, organizationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]category.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, organizationId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategories'
type MockService_GetCategories_Call struct {
	*mock.Call
}

// GetCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
func (_e *MockService_Expecter) GetCategories(ctx interface{}, organizationId interface{}) *MockService_GetCategories_Call {
	return &MockService_GetCategories_Call{Call: _e.mock.On("GetCategories", ctx, organizationId)}
}

func (_c *MockService_GetCategories_Call) Run(run func(ctx context.Context, organizationId int)) *MockService_GetCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetCategories_Call) Return(categorys []category.Category, err error) *MockService_GetCategories_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockService_GetCategories_Call) RunAndReturn(run func(ctx context.Context, organizationId int) ([]category.Category, error)) *MockService_GetCategories_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCategory provides a mock function for the type MockService
func (_mock *MockService) UpdateCategory(ctx context.Context, organizationId int, categoryId int, category1 category.UpdateCategory) error {
	ret := _mock.Called(ctx, organizationId, categoryId, category1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, category.UpdateCategory) error); ok {
		r0 = returnFunc(ctx, organizationId, categoryId, category1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCategory'
type MockService_UpdateCategory_Call struct {
	*mock.Call
}

// UpdateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - categoryId int
//   - category1 category.UpdateCategory
func (_e *MockService_Expecter) UpdateCategory(ctx interface{}, organizationId interface{}, categoryId interface{}, category1 interface{}) *MockService_UpdateCategory_Call {
	return &MockService_UpdateCategory_Call{Call: _e.mock.On("UpdateCategory", ctx, organizationId, categoryId, category1)}
}

func (_c *MockService_UpdateCategory_Call) Run(run func(ctx context.Context, organizationId int, categoryId int, category1 category.UpdateCategory)) *MockService_UpdateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 category.UpdateCategory
		if args[3] != nil {
			arg3 = args[3].(category.UpdateCategory)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UpdateCategory_Call) Return(err error) *MockService_UpdateCategory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateCategory_Call) RunAndReturn(run func(ctx context.Context, organizationId int, categoryId int, category1 category.UpdateCategory) error) *MockService_UpdateCategory_Call {
	_c.Call.Return(run)
	return _c
}
