all: true
dir: '{{.InterfaceDir}}/mocks'
structname: Mock{{.InterfaceName}}
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  planeo/services/core2/internal/domain/category:
    interfaces:
      CategoryRepository: {}
  planeo/services/core2/internal/domain/organization:
    interfaces:
      OrganizationRepository: {}
  planeo/services/core2/internal/domain/request:
    interfaces:
      RequestRepository: {}
  planeo/services/core2/internal/domain/user:
    interfaces:
      IAM: {}
      UserRepository: {}