// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"planeo/services/core/internal/domain/category"
	"planeo/services/core/internal/domain/inbox"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLLMClient creates a new instance of MockLLMClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLMClient {
	mock := &MockLLMClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLLMClient is an autogenerated mock type for the LLMClient type
type MockLLMClient struct {
	mock.Mock
}

type MockLLMClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLMClient) EXPECT() *MockLLMClient_Expecter {
	return &MockLLMClient_Expecter{mock: &_m.Mock}
}

// ClassifyRequest provides a mock function for the type MockLLMClient
func (_mock *MockLLMClient) ClassifyRequest(ctx context.Context, request inbox.RequestData, categories []category.Category) (int, error) {
	ret := _mock.Called(ctx, request, categories)

	if len(ret) == 0 {
		panic("no return value specified for ClassifyRequest")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbox.RequestData, []category.Category) (int, error)); ok {
		return returnFunc(ctx, request, categories)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbox.RequestData, []category.Category) int); ok {
		r0 = returnFunc(ctx, request, categories)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbox.RequestData, []category.Category) error); ok {
		r1 = returnFunc(ctx, request, categories)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLLMClient_ClassifyRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClassifyRequest'
type MockLLMClient_ClassifyRequest_Call struct {
	*mock.Call
}

// ClassifyRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - request inbox.RequestData
//   - categories []category.Category
func (_e *MockLLMClient_Expecter) ClassifyRequest(ctx interface{}, request interface{}, categories interface{}) *MockLLMClient_ClassifyRequest_Call {
	return &MockLLMClient_ClassifyRequest_Call{Call: _e.mock.On("ClassifyRequest", ctx, request, categories)}
}

func (_c *MockLLMClient_ClassifyRequest_Call) Run(run func(ctx context.Context, request inbox.RequestData, categories []category.Category)) *MockLLMClient_ClassifyRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbox.RequestData
		if args[1] != nil {
			arg1 = args[1].(inbox.RequestData)
		}
		var arg2 []category.Category
		if args[2] != nil {
			arg2 = args[2].([]category.Category)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLLMClient_ClassifyRequest_Call) Return(n int, err error) *MockLLMClient_ClassifyRequest_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLLMClient_ClassifyRequest_Call) RunAndReturn(run func(ctx context.Context, request inbox.RequestData, categories []category.Category) (int, error)) *MockLLMClient_ClassifyRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractRequestFields provides a mock function for the type MockLLMClient
func (_mock *MockLLMClient) ExtractRequestFields(ctx context.Context, requestText string) (inbox.ExtractorOutput, error) {
	ret := _mock.Called(ctx, requestText)

	if len(ret) == 0 {
		panic("no return value specified for ExtractRequestFields")
	}

	var r0 inbox.ExtractorOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (inbox.ExtractorOutput, error)); ok {
		return returnFunc(ctx, requestText)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) inbox.ExtractorOutput); ok {
		r0 = returnFunc(ctx, requestText)
	} else {
		r0 = ret.Get(0).(inbox.ExtractorOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, requestText)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLLMClient_ExtractRequestFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractRequestFields'
type MockLLMClient_ExtractRequestFields_Call struct {
	*mock.Call
}

// ExtractRequestFields is a helper method to define mock.On call
//   - ctx context.Context
//   - requestText string
func (_e *MockLLMClient_Expecter) ExtractRequestFields(ctx interface{}, requestText interface{}) *MockLLMClient_ExtractRequestFields_Call {
	return &MockLLMClient_ExtractRequestFields_Call{Call: _e.mock.On("ExtractRequestFields", ctx, requestText)}
}

func (_c *MockLLMClient_ExtractRequestFields_Call) Run(run func(ctx context.Context, requestText string)) *MockLLMClient_ExtractRequestFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLLMClient_ExtractRequestFields_Call) Return(extractorOutput inbox.ExtractorOutput, err error) *MockLLMClient_ExtractRequestFields_Call {
	_c.Call.Return(extractorOutput, err)
	return _c
}

func (_c *MockLLMClient_ExtractRequestFields_Call) RunAndReturn(run func(ctx context.Context, requestText string) (inbox.ExtractorOutput, error)) *MockLLMClient_ExtractRequestFields_Call {
	_c.Call.Return(run)
	return _c
}
