// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"planeo/libs/inbox"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// FetchBatch provides a mock function for the type MockRepository
func (_mock *MockRepository) FetchBatch(ctx context.Context, topic string, instanceID string, limit int, claimTTL time.Duration) ([]inbox.Record, error) {
	ret := _mock.Called(ctx, topic, instanceID, limit, claimTTL)

	if len(ret) == 0 {
		panic("no return value specified for FetchBatch")
	}

	var r0 []inbox.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, time.Duration) ([]inbox.Record, error)); ok {
		return returnFunc(ctx, topic, instanceID, limit, claimTTL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, time.Duration) []inbox.Record); ok {
		r0 = returnFunc(ctx, topic, instanceID, limit, claimTTL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]inbox.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, time.Duration) error); ok {
		r1 = returnFunc(ctx, topic, instanceID, limit, claimTTL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FetchBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchBatch'
type MockRepository_FetchBatch_Call struct {
	*mock.Call
}

// FetchBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - instanceID string
//   - limit int
//   - claimTTL time.Duration
func (_e *MockRepository_Expecter) FetchBatch(ctx interface{}, topic interface{}, instanceID interface{}, limit interface{}, claimTTL interface{}) *MockRepository_FetchBatch_Call {
	return &MockRepository_FetchBatch_Call{Call: _e.mock.On("FetchBatch", ctx, topic, instanceID, limit, claimTTL)}
}

func (_c *MockRepository_FetchBatch_Call) Run(run func(ctx context.Context, topic string, instanceID string, limit int, claimTTL time.Duration)) *MockRepository_FetchBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_FetchBatch_Call) Return(records []inbox.Record, err error) *MockRepository_FetchBatch_Call {
	_c.Call.Return(records, err)
	return _c
}

func (_c *MockRepository_FetchBatch_Call) RunAndReturn(run func(ctx context.Context, topic string, instanceID string, limit int, claimTTL time.Duration) ([]inbox.Record, error)) *MockRepository_FetchBatch_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkFailed(ctx context.Context, id int64, procErr error, maxAttempts int) error {
	ret := _mock.Called(ctx, id, procErr, maxAttempts)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, error, int) error); ok {
		r0 = returnFunc(ctx, id, procErr, maxAttempts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type MockRepository_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - procErr error
//   - maxAttempts int
func (_e *MockRepository_Expecter) MarkFailed(ctx interface{}, id interface{}, procErr interface{}, maxAttempts interface{}) *MockRepository_MarkFailed_Call {
	return &MockRepository_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, id, procErr, maxAttempts)}
}

func (_c *MockRepository_MarkFailed_Call) Run(run func(ctx context.Context, id int64, procErr error, maxAttempts int)) *MockRepository_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_MarkFailed_Call) Return(err error) *MockRepository_MarkFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkFailed_Call) RunAndReturn(run func(ctx context.Context, id int64, procErr error, maxAttempts int) error) *MockRepository_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessed provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkProcessed(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessed'
type MockRepository_MarkProcessed_Call struct {
	*mock.Call
}

// MarkProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepository_Expecter) MarkProcessed(ctx interface{}, id interface{}) *MockRepository_MarkProcessed_Call {
	return &MockRepository_MarkProcessed_Call{Call: _e.mock.On("MarkProcessed", ctx, id)}
}

func (_c *MockRepository_MarkProcessed_Call) Run(run func(ctx context.Context, id int64)) *MockRepository_MarkProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_MarkProcessed_Call) Return(err error) *MockRepository_MarkProcessed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkProcessed_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockRepository_MarkProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type MockRepository
func (_mock *MockRepository) WithTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockRepository_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockRepository_Expecter) WithTransaction(ctx interface{}, fn interface{}) *MockRepository_WithTransaction_Call {
	return &MockRepository_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *MockRepository_WithTransaction_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockRepository_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_WithTransaction_Call) Return(err error) *MockRepository_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockRepository_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
