// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"planeo/libs/inbox"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// FetchBatch provides a mock function for the type MockService
func (_mock *MockService) FetchBatch(ctx context.Context, topic string, instanceID string, limit int, claimTTL time.Duration) ([]inbox.Record, error) {
	ret := _mock.Called(ctx, topic, instanceID, limit, claimTTL)

	if len(ret) == 0 {
		panic("no return value specified for FetchBatch")
	}

	var r0 []inbox.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, time.Duration) ([]inbox.Record, error)); ok {
		return returnFunc(ctx, topic, instanceID, limit, claimTTL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, time.Duration) []inbox.Record); ok {
		r0 = returnFunc(ctx, topic, instanceID, limit, claimTTL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]inbox.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, time.Duration) error); ok {
		r1 = returnFunc(ctx, topic, instanceID, limit, claimTTL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_FetchBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchBatch'
type MockService_FetchBatch_Call struct {
	*mock.Call
}

// FetchBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - instanceID string
//   - limit int
//   - claimTTL time.Duration
func (_e *MockService_Expecter) FetchBatch(ctx interface{}, topic interface{}, instanceID interface{}, limit interface{}, claimTTL interface{}) *MockService_FetchBatch_Call {
	return &MockService_FetchBatch_Call{Call: _e.mock.On("FetchBatch", ctx, topic, instanceID, limit, claimTTL)}
}

func (_c *MockService_FetchBatch_Call) Run(run func(ctx context.Context, topic string, instanceID string, limit int, claimTTL time.Duration)) *MockService_FetchBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_FetchBatch_Call) Return(records []inbox.Record, err error) *MockService_FetchBatch_Call {
	_c.Call.Return(records, err)
	return _c
}

func (_c *MockService_FetchBatch_Call) RunAndReturn(run func(ctx context.Context, topic string, instanceID string, limit int, claimTTL time.Duration) ([]inbox.Record, error)) *MockService_FetchBatch_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessEmailReceived provides a mock function for the type MockService
func (_mock *MockService) ProcessEmailReceived(ctx context.Context, rec inbox.Record, maxAttempts int) error {
	ret := _mock.Called(ctx, rec, maxAttempts)

	if len(ret) == 0 {
		panic("no return value specified for ProcessEmailReceived")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbox.Record, int) error); ok {
		r0 = returnFunc(ctx, rec, maxAttempts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ProcessEmailReceived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessEmailReceived'
type MockService_ProcessEmailReceived_Call struct {
	*mock.Call
}

// ProcessEmailReceived is a helper method to define mock.On call
//   - ctx context.Context
//   - rec inbox.Record
//   - maxAttempts int
func (_e *MockService_Expecter) ProcessEmailReceived(ctx interface{}, rec interface{}, maxAttempts interface{}) *MockService_ProcessEmailReceived_Call {
	return &MockService_ProcessEmailReceived_Call{Call: _e.mock.On("ProcessEmailReceived", ctx, rec, maxAttempts)}
}

func (_c *MockService_ProcessEmailReceived_Call) Run(run func(ctx context.Context, rec inbox.Record, maxAttempts int)) *MockService_ProcessEmailReceived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbox.Record
		if args[1] != nil {
			arg1 = args[1].(inbox.Record)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ProcessEmailReceived_Call) Return(err error) *MockService_ProcessEmailReceived_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ProcessEmailReceived_Call) RunAndReturn(run func(ctx context.Context, rec inbox.Record, maxAttempts int) error) *MockService_ProcessEmailReceived_Call {
	_c.Call.Return(run)
	return _c
}
