// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"planeo/services/core/internal/domain/user"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIAM creates a new instance of MockIAM. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAM(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAM {
	mock := &MockIAM{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAM is an autogenerated mock type for the IAM type
type MockIAM struct {
	mock.Mock
}

type MockIAM_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAM) EXPECT() *MockIAM_Expecter {
	return &MockIAM_Expecter{mock: &_m.Mock}
}

// AssignRolesToUser provides a mock function for the type MockIAM
func (_mock *MockIAM) AssignRolesToUser(ctx context.Context, organizationIamIdentifier string, uuid string, roles []user.Role) error {
	ret := _mock.Called(ctx, organizationIamIdentifier, uuid, roles)

	if len(ret) == 0 {
		panic("no return value specified for AssignRolesToUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []user.Role) error); ok {
		r0 = returnFunc(ctx, organizationIamIdentifier, uuid, roles)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAM_AssignRolesToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRolesToUser'
type MockIAM_AssignRolesToUser_Call struct {
	*mock.Call
}

// AssignRolesToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationIamIdentifier string
//   - uuid string
//   - roles []user.Role
func (_e *MockIAM_Expecter) AssignRolesToUser(ctx interface{}, organizationIamIdentifier interface{}, uuid interface{}, roles interface{}) *MockIAM_AssignRolesToUser_Call {
	return &MockIAM_AssignRolesToUser_Call{Call: _e.mock.On("AssignRolesToUser", ctx, organizationIamIdentifier, uuid, roles)}
}

func (_c *MockIAM_AssignRolesToUser_Call) Run(run func(ctx context.Context, organizationIamIdentifier string, uuid string, roles []user.Role)) *MockIAM_AssignRolesToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []user.Role
		if args[3] != nil {
			arg3 = args[3].([]user.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIAM_AssignRolesToUser_Call) Return(err error) *MockIAM_AssignRolesToUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAM_AssignRolesToUser_Call) RunAndReturn(run func(ctx context.Context, organizationIamIdentifier string, uuid string, roles []user.Role) error) *MockIAM_AssignRolesToUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockIAM
func (_mock *MockIAM) CreateUser(ctx context.Context, organizationIamIdentifier string, newUser user.NewUser) (*user.IAMUser, error) {
	ret := _mock.Called(ctx, organizationIamIdentifier, newUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *user.IAMUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, user.NewUser) (*user.IAMUser, error)); ok {
		return returnFunc(ctx, organizationIamIdentifier, newUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, user.NewUser) *user.IAMUser); ok {
		r0 = returnFunc(ctx, organizationIamIdentifier, newUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.IAMUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, user.NewUser) error); ok {
		r1 = returnFunc(ctx, organizationIamIdentifier, newUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAM_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIAM_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationIamIdentifier string
//   - newUser user.NewUser
func (_e *MockIAM_Expecter) CreateUser(ctx interface{}, organizationIamIdentifier interface{}, newUser interface{}) *MockIAM_CreateUser_Call {
	return &MockIAM_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, organizationIamIdentifier, newUser)}
}

func (_c *MockIAM_CreateUser_Call) Run(run func(ctx context.Context, organizationIamIdentifier string, newUser user.NewUser)) *MockIAM_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 user.NewUser
		if args[2] != nil {
			arg2 = args[2].(user.NewUser)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAM_CreateUser_Call) Return(iAMUser *user.IAMUser, err error) *MockIAM_CreateUser_Call {
	_c.Call.Return(iAMUser, err)
	return _c
}

func (_c *MockIAM_CreateUser_Call) RunAndReturn(run func(ctx context.Context, organizationIamIdentifier string, newUser user.NewUser) (*user.IAMUser, error)) *MockIAM_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockIAM
func (_mock *MockIAM) DeleteUser(ctx context.Context, organizationIamIdentifier string, uuid string) error {
	ret := _mock.Called(ctx, organizationIamIdentifier, uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, organizationIamIdentifier, uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAM_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockIAM_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationIamIdentifier string
//   - uuid string
func (_e *MockIAM_Expecter) DeleteUser(ctx interface{}, organizationIamIdentifier interface{}, uuid interface{}) *MockIAM_DeleteUser_Call {
	return &MockIAM_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, organizationIamIdentifier, uuid)}
}

func (_c *MockIAM_DeleteUser_Call) Run(run func(ctx context.Context, organizationIamIdentifier string, uuid string)) *MockIAM_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAM_DeleteUser_Call) Return(err error) *MockIAM_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAM_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, organizationIamIdentifier string, uuid string) error) *MockIAM_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoles provides a mock function for the type MockIAM
func (_mock *MockIAM) GetRoles(ctx context.Context) ([]user.Role, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRoles")
	}

	var r0 []user.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]user.Role, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []user.Role); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAM_GetRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoles'
type MockIAM_GetRoles_Call struct {
	*mock.Call
}

// GetRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIAM_Expecter) GetRoles(ctx interface{}) *MockIAM_GetRoles_Call {
	return &MockIAM_GetRoles_Call{Call: _e.mock.On("GetRoles", ctx)}
}

func (_c *MockIAM_GetRoles_Call) Run(run func(ctx context.Context)) *MockIAM_GetRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIAM_GetRoles_Call) Return(roles []user.Role, err error) *MockIAM_GetRoles_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockIAM_GetRoles_Call) RunAndReturn(run func(ctx context.Context) ([]user.Role, error)) *MockIAM_GetRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function for the type MockIAM
func (_mock *MockIAM) GetUserById(ctx context.Context, organizationIamIdentifier string, uuid string) (*user.IAMUser, error) {
	ret := _mock.Called(ctx, organizationIamIdentifier, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *user.IAMUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*user.IAMUser, error)); ok {
		return returnFunc(ctx, organizationIamIdentifier, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *user.IAMUser); ok {
		r0 = returnFunc(ctx, organizationIamIdentifier, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.IAMUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, organizationIamIdentifier, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAM_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type MockIAM_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationIamIdentifier string
//   - uuid string
func (_e *MockIAM_Expecter) GetUserById(ctx interface{}, organizationIamIdentifier interface{}, uuid interface{}) *MockIAM_GetUserById_Call {
	return &MockIAM_GetUserById_Call{Call: _e.mock.On("GetUserById", ctx, organizationIamIdentifier, uuid)}
}

func (_c *MockIAM_GetUserById_Call) Run(run func(ctx context.Context, organizationIamIdentifier string, uuid string)) *MockIAM_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAM_GetUserById_Call) Return(iAMUser *user.IAMUser, err error) *MockIAM_GetUserById_Call {
	_c.Call.Return(iAMUser, err)
	return _c
}

func (_c *MockIAM_GetUserById_Call) RunAndReturn(run func(ctx context.Context, organizationIamIdentifier string, uuid string) (*user.IAMUser, error)) *MockIAM_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockIAM
func (_mock *MockIAM) GetUsers(ctx context.Context, organizationIamIdentifier string) ([]user.IAMUser, error) {
	ret := _mock.Called(ctx, organizationIamIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []user.IAMUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]user.IAMUser, error)); ok {
		return returnFunc(ctx, organizationIamIdentifier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []user.IAMUser); ok {
		r0 = returnFunc(ctx, organizationIamIdentifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.IAMUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, organizationIamIdentifier)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAM_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockIAM_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationIamIdentifier string
func (_e *MockIAM_Expecter) GetUsers(ctx interface{}, organizationIamIdentifier interface{}) *MockIAM_GetUsers_Call {
	return &MockIAM_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, organizationIamIdentifier)}
}

func (_c *MockIAM_GetUsers_Call) Run(run func(ctx context.Context, organizationIamIdentifier string)) *MockIAM_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAM_GetUsers_Call) Return(iAMUsers []user.IAMUser, err error) *MockIAM_GetUsers_Call {
	_c.Call.Return(iAMUsers, err)
	return _c
}

func (_c *MockIAM_GetUsers_Call) RunAndReturn(run func(ctx context.Context, organizationIamIdentifier string) ([]user.IAMUser, error)) *MockIAM_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockIAM
func (_mock *MockIAM) UpdateUser(ctx context.Context, organizationIamIdentifier string, uuid string, updateUser user.UpdateUser) error {
	ret := _mock.Called(ctx, organizationIamIdentifier, uuid, updateUser)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, user.UpdateUser) error); ok {
		r0 = returnFunc(ctx, organizationIamIdentifier, uuid, updateUser)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAM_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockIAM_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationIamIdentifier string
//   - uuid string
//   - updateUser user.UpdateUser
func (_e *MockIAM_Expecter) UpdateUser(ctx interface{}, organizationIamIdentifier interface{}, uuid interface{}, updateUser interface{}) *MockIAM_UpdateUser_Call {
	return &MockIAM_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, organizationIamIdentifier, uuid, updateUser)}
}

func (_c *MockIAM_UpdateUser_Call) Run(run func(ctx context.Context, organizationIamIdentifier string, uuid string, updateUser user.UpdateUser)) *MockIAM_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 user.UpdateUser
		if args[3] != nil {
			arg3 = args[3].(user.UpdateUser)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIAM_UpdateUser_Call) Return(err error) *MockIAM_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAM_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, organizationIamIdentifier string, uuid string, updateUser user.UpdateUser) error) *MockIAM_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
