// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"planeo/services/core/internal/domain/user"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AssignRoles provides a mock function for the type MockService
func (_mock *MockService) AssignRoles(ctx context.Context, organizationId int, uuid string, roles []user.Role) error {
	ret := _mock.Called(ctx, organizationId, uuid, roles)

	if len(ret) == 0 {
		panic("no return value specified for AssignRoles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, []user.Role) error); ok {
		r0 = returnFunc(ctx, organizationId, uuid, roles)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AssignRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRoles'
type MockService_AssignRoles_Call struct {
	*mock.Call
}

// AssignRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - uuid string
//   - roles []user.Role
func (_e *MockService_Expecter) AssignRoles(ctx interface{}, organizationId interface{}, uuid interface{}, roles interface{}) *MockService_AssignRoles_Call {
	return &MockService_AssignRoles_Call{Call: _e.mock.On("AssignRoles", ctx, organizationId, uuid, roles)}
}

func (_c *MockService_AssignRoles_Call) Run(run func(ctx context.Context, organizationId int, uuid string, roles []user.Role)) *MockService_AssignRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []user.Role
		if args[3] != nil {
			arg3 = args[3].([]user.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_AssignRoles_Call) Return(err error) *MockService_AssignRoles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AssignRoles_Call) RunAndReturn(run func(ctx context.Context, organizationId int, uuid string, roles []user.Role) error) *MockService_AssignRoles_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockService
func (_mock *MockService) CreateUser(ctx context.Context, organizationId int, newUser user.NewUser) error {
	ret := _mock.Called(ctx, organizationId, newUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, user.NewUser) error); ok {
		r0 = returnFunc(ctx, organizationId, newUser)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - newUser user.NewUser
func (_e *MockService_Expecter) CreateUser(ctx interface{}, organizationId interface{}, newUser interface{}) *MockService_CreateUser_Call {
	return &MockService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, organizationId, newUser)}
}

func (_c *MockService_CreateUser_Call) Run(run func(ctx context.Context, organizationId int, newUser user.NewUser)) *MockService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 user.NewUser
		if args[2] != nil {
			arg2 = args[2].(user.NewUser)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CreateUser_Call) Return(err error) *MockService_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, organizationId int, newUser user.NewUser) error) *MockService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockService
func (_mock *MockService) DeleteUser(ctx context.Context, organizationId int, uuid string) error {
	ret := _mock.Called(ctx, organizationId, uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, organizationId, uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - uuid string
func (_e *MockService_Expecter) DeleteUser(ctx interface{}, organizationId interface{}, uuid interface{}) *MockService_DeleteUser_Call {
	return &MockService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, organizationId, uuid)}
}

func (_c *MockService_DeleteUser_Call) Run(run func(ctx context.Context, organizationId int, uuid string)) *MockService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteUser_Call) Return(err error) *MockService_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, organizationId int, uuid string) error) *MockService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvailableRoles provides a mock function for the type MockService
func (_mock *MockService) GetAvailableRoles(ctx context.Context) ([]user.Role, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableRoles")
	}

	var r0 []user.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]user.Role, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []user.Role); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetAvailableRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableRoles'
type MockService_GetAvailableRoles_Call struct {
	*mock.Call
}

// GetAvailableRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetAvailableRoles(ctx interface{}) *MockService_GetAvailableRoles_Call {
	return &MockService_GetAvailableRoles_Call{Call: _e.mock.On("GetAvailableRoles", ctx)}
}

func (_c *MockService_GetAvailableRoles_Call) Run(run func(ctx context.Context)) *MockService_GetAvailableRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetAvailableRoles_Call) Return(roles []user.Role, err error) *MockService_GetAvailableRoles_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockService_GetAvailableRoles_Call) RunAndReturn(run func(ctx context.Context) ([]user.Role, error)) *MockService_GetAvailableRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetIAMUserByUuid provides a mock function for the type MockService
func (_mock *MockService) GetIAMUserByUuid(ctx context.Context, organizationId int, uuid string) (*user.IAMUser, error) {
	ret := _mock.Called(ctx, organizationId, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetIAMUserByUuid")
	}

	var r0 *user.IAMUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) (*user.IAMUser, error)); ok {
		return returnFunc(ctx, organizationId, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) *user.IAMUser); ok {
		r0 = returnFunc(ctx, organizationId, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.IAMUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, organizationId, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetIAMUserByUuid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIAMUserByUuid'
type MockService_GetIAMUserByUuid_Call struct {
	*mock.Call
}

// GetIAMUserByUuid is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - uuid string
func (_e *MockService_Expecter) GetIAMUserByUuid(ctx interface{}, organizationId interface{}, uuid interface{}) *MockService_GetIAMUserByUuid_Call {
	return &MockService_GetIAMUserByUuid_Call{Call: _e.mock.On("GetIAMUserByUuid", ctx, organizationId, uuid)}
}

func (_c *MockService_GetIAMUserByUuid_Call) Run(run func(ctx context.Context, organizationId int, uuid string)) *MockService_GetIAMUserByUuid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetIAMUserByUuid_Call) Return(iAMUser *user.IAMUser, err error) *MockService_GetIAMUserByUuid_Call {
	_c.Call.Return(iAMUser, err)
	return _c
}

func (_c *MockService_GetIAMUserByUuid_Call) RunAndReturn(run func(ctx context.Context, organizationId int, uuid string) (*user.IAMUser, error)) *MockService_GetIAMUserByUuid_Call {
	_c.Call.Return(run)
	return _c
}

// GetIAMUsers provides a mock function for the type MockService
func (_mock *MockService) GetIAMUsers(ctx context.Context, organizationId int, sync bool) ([]user.IAMUser, error) {
	ret := _mock.Called(ctx, organizationId, sync)

	if len(ret) == 0 {
		panic("no return value specified for GetIAMUsers")
	}

	var r0 []user.IAMUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) ([]user.IAMUser, error)); ok {
		return returnFunc(ctx, organizationId, sync)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) []user.IAMUser); ok {
		r0 = returnFunc(ctx, organizationId, sync)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.IAMUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, bool) error); ok {
		r1 = returnFunc(ctx, organizationId, sync)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetIAMUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIAMUsers'
type MockService_GetIAMUsers_Call struct {
	*mock.Call
}

// GetIAMUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - sync bool
func (_e *MockService_Expecter) GetIAMUsers(ctx interface{}, organizationId interface{}, sync interface{}) *MockService_GetIAMUsers_Call {
	return &MockService_GetIAMUsers_Call{Call: _e.mock.On("GetIAMUsers", ctx, organizationId, sync)}
}

func (_c *MockService_GetIAMUsers_Call) Run(run func(ctx context.Context, organizationId int, sync bool)) *MockService_GetIAMUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetIAMUsers_Call) Return(iAMUsers []user.IAMUser, err error) *MockService_GetIAMUsers_Call {
	_c.Call.Return(iAMUsers, err)
	return _c
}

func (_c *MockService_GetIAMUsers_Call) RunAndReturn(run func(ctx context.Context, organizationId int, sync bool) ([]user.IAMUser, error)) *MockService_GetIAMUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockService
func (_mock *MockService) GetUsers(ctx context.Context, organizationId int) ([]user.User, error) {
	ret := _mock.Called(ctx, organizationId)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]user.User, error)); ok {
		return returnFunc(ctx, organizationId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []user.User); ok {
		r0 = returnFunc(ctx, organizationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, organizationId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockService_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
func (_e *MockService_Expecter) GetUsers(ctx interface{}, organizationId interface{}) *MockService_GetUsers_Call {
	return &MockService_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, organizationId)}
}

func (_c *MockService_GetUsers_Call) Run(run func(ctx context.Context, organizationId int)) *MockService_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetUsers_Call) Return(users []user.User, err error) *MockService_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockService_GetUsers_Call) RunAndReturn(run func(ctx context.Context, organizationId int) ([]user.User, error)) *MockService_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockService
func (_mock *MockService) UpdateUser(ctx context.Context, organizationId int, uuid string, user1 user.UpdateUser) error {
	ret := _mock.Called(ctx, organizationId, uuid, user1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, user.UpdateUser) error); ok {
		r0 = returnFunc(ctx, organizationId, uuid, user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockService_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - uuid string
//   - user1 user.UpdateUser
func (_e *MockService_Expecter) UpdateUser(ctx interface{}, organizationId interface{}, uuid interface{}, user1 interface{}) *MockService_UpdateUser_Call {
	return &MockService_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, organizationId, uuid, user1)}
}

func (_c *MockService_UpdateUser_Call) Run(run func(ctx context.Context, organizationId int, uuid string, user1 user.UpdateUser)) *MockService_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 user.UpdateUser
		if args[3] != nil {
			arg3 = args[3].(user.UpdateUser)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UpdateUser_Call) Return(err error) *MockService_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, organizationId int, uuid string, user1 user.UpdateUser) error) *MockService_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
