// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"planeo/services/core/internal/domain/user"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) CreateUser(ctx context.Context, organizationId int, uuid string, user1 user.NewUser) error {
	ret := _mock.Called(ctx, organizationId, uuid, user1)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, user.NewUser) error); ok {
		r0 = returnFunc(ctx, organizationId, uuid, user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - uuid string
//   - user1 user.NewUser
func (_e *MockUserRepository_Expecter) CreateUser(ctx interface{}, organizationId interface{}, uuid interface{}, user1 interface{}) *MockUserRepository_CreateUser_Call {
	return &MockUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, organizationId, uuid, user1)}
}

func (_c *MockUserRepository_CreateUser_Call) Run(run func(ctx context.Context, organizationId int, uuid string, user1 user.NewUser)) *MockUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 user.NewUser
		if args[3] != nil {
			arg3 = args[3].(user.NewUser)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) Return(err error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, organizationId int, uuid string, user1 user.NewUser) error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) DeleteUser(ctx context.Context, organizationId int, uuid string) error {
	ret := _mock.Called(ctx, organizationId, uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, organizationId, uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - uuid string
func (_e *MockUserRepository_Expecter) DeleteUser(ctx interface{}, organizationId interface{}, uuid interface{}) *MockUserRepository_DeleteUser_Call {
	return &MockUserRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, organizationId, uuid)}
}

func (_c *MockUserRepository_DeleteUser_Call) Run(run func(ctx context.Context, organizationId int, uuid string)) *MockUserRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_DeleteUser_Call) Return(err error) *MockUserRepository_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, organizationId int, uuid string) error) *MockUserRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetIamOrganizationIdentifier provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetIamOrganizationIdentifier(ctx context.Context, organizationId int) (string, error) {
	ret := _mock.Called(ctx, organizationId)

	if len(ret) == 0 {
		panic("no return value specified for GetIamOrganizationIdentifier")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, error)); ok {
		return returnFunc(ctx, organizationId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(ctx, organizationId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, organizationId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetIamOrganizationIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIamOrganizationIdentifier'
type MockUserRepository_GetIamOrganizationIdentifier_Call struct {
	*mock.Call
}

// GetIamOrganizationIdentifier is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
func (_e *MockUserRepository_Expecter) GetIamOrganizationIdentifier(ctx interface{}, organizationId interface{}) *MockUserRepository_GetIamOrganizationIdentifier_Call {
	return &MockUserRepository_GetIamOrganizationIdentifier_Call{Call: _e.mock.On("GetIamOrganizationIdentifier", ctx, organizationId)}
}

func (_c *MockUserRepository_GetIamOrganizationIdentifier_Call) Run(run func(ctx context.Context, organizationId int)) *MockUserRepository_GetIamOrganizationIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetIamOrganizationIdentifier_Call) Return(s string, err error) *MockUserRepository_GetIamOrganizationIdentifier_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserRepository_GetIamOrganizationIdentifier_Call) RunAndReturn(run func(ctx context.Context, organizationId int) (string, error)) *MockUserRepository_GetIamOrganizationIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUsers(ctx context.Context, organizationId int) ([]user.User, error) {
	ret := _mock.Called(ctx, organizationId)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]user.User, error)); ok {
		return returnFunc(ctx, organizationId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []user.User); ok {
		r0 = returnFunc(ctx, organizationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, organizationId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUserRepository_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
func (_e *MockUserRepository_Expecter) GetUsers(ctx interface{}, organizationId interface{}) *MockUserRepository_GetUsers_Call {
	return &MockUserRepository_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, organizationId)}
}

func (_c *MockUserRepository_GetUsers_Call) Run(run func(ctx context.Context, organizationId int)) *MockUserRepository_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUsers_Call) Return(users []user.User, err error) *MockUserRepository_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepository_GetUsers_Call) RunAndReturn(run func(ctx context.Context, organizationId int) ([]user.User, error)) *MockUserRepository_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SyncUsers provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) SyncUsers(ctx context.Context, organizationId int, users []user.IAMUser) error {
	ret := _mock.Called(ctx, organizationId, users)

	if len(ret) == 0 {
		panic("no return value specified for SyncUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []user.IAMUser) error); ok {
		r0 = returnFunc(ctx, organizationId, users)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_SyncUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncUsers'
type MockUserRepository_SyncUsers_Call struct {
	*mock.Call
}

// SyncUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - users []user.IAMUser
func (_e *MockUserRepository_Expecter) SyncUsers(ctx interface{}, organizationId interface{}, users interface{}) *MockUserRepository_SyncUsers_Call {
	return &MockUserRepository_SyncUsers_Call{Call: _e.mock.On("SyncUsers", ctx, organizationId, users)}
}

func (_c *MockUserRepository_SyncUsers_Call) Run(run func(ctx context.Context, organizationId int, users []user.IAMUser)) *MockUserRepository_SyncUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []user.IAMUser
		if args[2] != nil {
			arg2 = args[2].([]user.IAMUser)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_SyncUsers_Call) Return(err error) *MockUserRepository_SyncUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_SyncUsers_Call) RunAndReturn(run func(ctx context.Context, organizationId int, users []user.IAMUser) error) *MockUserRepository_SyncUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UpdateUser(ctx context.Context, organizationId int, uuid string, user1 user.UpdateUser) error {
	ret := _mock.Called(ctx, organizationId, uuid, user1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, user.UpdateUser) error); ok {
		r0 = returnFunc(ctx, organizationId, uuid, user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId int
//   - uuid string
//   - user1 user.UpdateUser
func (_e *MockUserRepository_Expecter) UpdateUser(ctx interface{}, organizationId interface{}, uuid interface{}, user1 interface{}) *MockUserRepository_UpdateUser_Call {
	return &MockUserRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, organizationId, uuid, user1)}
}

func (_c *MockUserRepository_UpdateUser_Call) Run(run func(ctx context.Context, organizationId int, uuid string, user1 user.UpdateUser)) *MockUserRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 user.UpdateUser
		if args[3] != nil {
			arg3 = args[3].(user.UpdateUser)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepository_UpdateUser_Call) Return(err error) *MockUserRepository_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, organizationId int, uuid string, user1 user.UpdateUser) error) *MockUserRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
