name: "Backend Test"
run-name: Build backend service on ${{ github.ref }}
on:
  push:
    paths:
      - backend/**
jobs:
  backend-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
      - name: Check Go formatting
        run: |
          unformatted_files=$(gofmt -l .)
          if [ -n "$unformatted_files" ]; then
            echo "The following files are not correctly formatted:"
            echo "$unformatted_files"
            echo "Run 'gofmt -w .' to fix formatting."
            exit 1
          fi
