name: "Backend Build"
run-name: Build backend service on ${{ github.ref }}
on:
  push:
    branches:
      - main
      - 20-add-basic-ci-pipeline
    paths:
      - backend/**
  pull_request:
    branches:
      - main
    paths:
      - backend/**
jobs:
  print-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print GitHub context
        run: echo "${{ toJson(github) }}"