name: "Core Test"
run-name: Build core service on ${{ github.ref }}
on:
  push:
    paths:
      - services/core/**
      - .golangci.yml
      - .github/workflows/**
  workflow_call:

jobs:
  core-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.5
          cache: true
      - name: Verify Go module consistency
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

  core-lint:
    runs-on: ubuntu-latest
    needs: core-dependencies
    defaults:
      run:
        working-directory: ./services/core
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.5
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          working-directory: ./services/core
          args: --config ../../.golangci.yml

  core-unit-test:
    runs-on: ubuntu-latest
    needs: core-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.5
      - name: Install Task
        uses: go-task/setup-task@v1
      - name: Run unit tests
        run: task test:core:unit

  core-integration-test:
    runs-on: ubuntu-latest
    needs: core-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.5
      - name: Install Task
        uses: go-task/setup-task@v1
      - name: Install goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
      - name: Run integration tests
        run: task test:core:integration
