name: "Core Test"
run-name: Build core service on ${{ github.ref }}
on:
  push:
    paths:
      - services/core/**
  workflow_call:

jobs:
  core-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Verify Go module consistency
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

  core-format:
    runs-on: ubuntu-latest
    needs: core-dependencies
    defaults:
      run:
        working-directory: ./services/core
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Check Go formatting
        run: |
          unformatted_files=$(gofmt -l .)
          if [ -n "$unformatted_files" ]; then
            echo "The following files are not correctly formatted:"
            echo "$unformatted_files"
            echo "Run 'gofmt -w .' to fix formatting."
            exit 1
          fi
      - name: Check Go imports
        run: |
          unformatted_files=$(goimports -l .)
          if [ -n "$unformatted_files" ]; then
            echo "The following files have incorrect imports:"
            echo "$unformatted_files"
            echo "Run 'goimports -w .' to fix imports."
            exit 1
          fi

  core-vet:
    runs-on: ubuntu-latest
    needs: core-dependencies
    defaults:
      run:
        working-directory: ./services/core
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
      - name: Check Go vet
        run: go vet ./...

  core-unit-test:
    runs-on: ubuntu-latest
    needs: core-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
      - name: Run unit tests
        run: make test core unit

  core-integration-test:
    runs-on: ubuntu-latest
    needs: core-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
      - name: Install goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
      - name: Run integration tests
        run: make test core integration
