name: "Backend Release to Dev"
run-name: "Backend Release to Dev"
on:
    workflow_dispatch:
        inputs:
            ref:
                description: "Reference of the commit to release"
                required: true

env:
  REGISTRY: ghcr.io
  Account: antoniomartinezlopez
  IMAGE_NAME: planeo-core

permissions:
    contents: read
    packages: write
    attestations: write
    id-token: write

jobs:
    test-core:
        uses: ./.github/workflows/core-test.yml
    build-container-image:
        runs-on: ubuntu-latest
        needs: test-core
        defaults:
            run:
                working-directory: ./services/core
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
              with:
                context: ./services/core
                push: true
                tags: ${{ env.REGISTRY }}/${{ env.Account }}/${{ env.IMAGE_NAME }}:${{ inputs.ref}}
            
