// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"planeo/services/core/internal/domain/organization"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrganizationRepository creates a new instance of MockOrganizationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationRepository {
	mock := &MockOrganizationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrganizationRepository is an autogenerated mock type for the OrganizationRepository type
type MockOrganizationRepository struct {
	mock.Mock
}

type MockOrganizationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationRepository) EXPECT() *MockOrganizationRepository_Expecter {
	return &MockOrganizationRepository_Expecter{mock: &_m.Mock}
}

// GetOrganizationById provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) GetOrganizationById(ctx context.Context, id int) (organization.Organization, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationById")
	}

	var r0 organization.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (organization.Organization, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) organization.Organization); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(organization.Organization)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_GetOrganizationById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationById'
type MockOrganizationRepository_GetOrganizationById_Call struct {
	*mock.Call
}

// GetOrganizationById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockOrganizationRepository_Expecter) GetOrganizationById(ctx interface{}, id interface{}) *MockOrganizationRepository_GetOrganizationById_Call {
	return &MockOrganizationRepository_GetOrganizationById_Call{Call: _e.mock.On("GetOrganizationById", ctx, id)}
}

func (_c *MockOrganizationRepository_GetOrganizationById_Call) Run(run func(ctx context.Context, id int)) *MockOrganizationRepository_GetOrganizationById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_GetOrganizationById_Call) Return(organization1 organization.Organization, err error) *MockOrganizationRepository_GetOrganizationById_Call {
	_c.Call.Return(organization1, err)
	return _c
}

func (_c *MockOrganizationRepository_GetOrganizationById_Call) RunAndReturn(run func(ctx context.Context, id int) (organization.Organization, error)) *MockOrganizationRepository_GetOrganizationById_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationsByUserSub provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) GetOrganizationsByUserSub(ctx context.Context, userSub string) ([]organization.Organization, error) {
	ret := _mock.Called(ctx, userSub)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationsByUserSub")
	}

	var r0 []organization.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]organization.Organization, error)); ok {
		return returnFunc(ctx, userSub)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []organization.Organization); ok {
		r0 = returnFunc(ctx, userSub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]organization.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userSub)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_GetOrganizationsByUserSub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationsByUserSub'
type MockOrganizationRepository_GetOrganizationsByUserSub_Call struct {
	*mock.Call
}

// GetOrganizationsByUserSub is a helper method to define mock.On call
//   - ctx context.Context
//   - userSub string
func (_e *MockOrganizationRepository_Expecter) GetOrganizationsByUserSub(ctx interface{}, userSub interface{}) *MockOrganizationRepository_GetOrganizationsByUserSub_Call {
	return &MockOrganizationRepository_GetOrganizationsByUserSub_Call{Call: _e.mock.On("GetOrganizationsByUserSub", ctx, userSub)}
}

func (_c *MockOrganizationRepository_GetOrganizationsByUserSub_Call) Run(run func(ctx context.Context, userSub string)) *MockOrganizationRepository_GetOrganizationsByUserSub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_GetOrganizationsByUserSub_Call) Return(organizations []organization.Organization, err error) *MockOrganizationRepository_GetOrganizationsByUserSub_Call {
	_c.Call.Return(organizations, err)
	return _c
}

func (_c *MockOrganizationRepository_GetOrganizationsByUserSub_Call) RunAndReturn(run func(ctx context.Context, userSub string) ([]organization.Organization, error)) *MockOrganizationRepository_GetOrganizationsByUserSub_Call {
	_c.Call.Return(run)
	return _c
}
